### PR TITLE
Fix the tests to match the Linter v2 spec.

### PR DESCRIPTION
**Pull request by timmyers**
This PR fixes the tests that were failing by updating them to match the Linter V2 spec that is now implemented.

This should hopefully fix the Travis build as well.

### CODE REVIEW

**Comment by mschuchard** [comment]
Wow you got this working? My linters are almost exclusively the only ones using the v2 API, and I was going to wait for another linter maintainer to figure this out and just "borrow" from that since my `node.js` and `jasmine` skills are low-level. You may be the first person to figure this out.

Mad props; you are awesome.

**Comment by timmyers** [comment]
Really?  I'm definitely not in this space much at all, but I thought the v2 API was pretty prevalent and most packages had upgraded.

In any case, fixing the tests was just a matter of following http://steelbrain.me/linter/guides/upgrading-to-standard-linter-v2.html to update the tests.

Much easier than when you actually implemented them (https://github.com/mschuchard/linter-terraform-syntax/commit/08a14d54c87809402d8c491e4e61e3fb4b62dc91) I would think haha!

Thanks for the super fast merge though!  Always nice get the build passing, hope I can find some more way to contribute in the future.

**Comment by Arcanemagus** [comment]
As @timmyers fixing the specs is just as simple as updating to the v2 API, and yours are definitely not the only providers on the v2 API @mschuchard 😛.

**Comment by mschuchard** [comment]
@Arcanemagus For an expert `node.js` developer like you, yes it would be that simple. Not so much for a polyglot like me where `node.js` is below my top ten (maybe even top fifteen) in experience. Also, I know mine are not the only one, but when I looked around to try to find an example of someone on the v2 API so I could follow an example to update my specs, I could not find anyone who had done so. Maybe there has been a large migration in the last few months since then.

**Comment by Arcanemagus** [comment]
Yea, I think yours were some of the first, it's grown a lot more since then. I haven't made a huge push to upgrade it since v1 is still supported (and some are impossible to migrate to v2).

**Pull request merged**
